Fix "NameError: global name 'install_deb_package' is not defined"
[Issue] N/A
[Problem] on clean Ubuntu 18.04, launch script reports error:
    NameError: global name 'install_deb_package' is not defined
[Cause] install_deb_package is not defined when import_additional
    function is called.
[Solution] Move import_additional to main.
[Test]
    1. Before applying the patch do:
        -sudo apt-get remove python-pip
    2. You should see:
        NameError: global name 'install_deb_package' is not defined
    3. Apply the patch.
    4. python-pip should be installed automatically and WATT should start.

Signed-off-by: Grzegorz Czajkowski <g.czajkowski@samsung.com>